### PR TITLE
Use rule.append rather than manual node creation

### LINKED ISSUE #71: Don't set Container#nodes directly
You should set children by `append()` or any other inset methods (of course, except `push()`).

Here we have same problem as with `push()`: PostCSS will not fix issues for you as result it is easy to broke AST.

In result we have issue in other PostCSS plugins like this: https://github.com/ben-eb/cssnano/issues/163#issuecomment-208214467

### PR DESCRIPTION
**Pull request by just-boris**
closes #71
initial credits goes to #73

### CODE REVIEW

**Comment by ai** [comment]
@geelen I confirm that it is a safer way. LGTM

**Comment by just-boris** [comment]
Build is now green, by the way

**Comment by geelen** [comment]
😍

**Comment by ben-eb** [comment]
Thanks! 😄

**Pull request merged**
