### PR TITLE
fix(package): add license file

### PR DESCRIPTION
**Pull request by patricksmms**
Ref https://github.com/webpack-contrib/css-loader/issues/786

This needs to be published in npm to `postcss-modules-scope@1.1.1`

### CODE REVIEW

**Comment by alexander-akait** [comment]
Invalid license, in `package.json` it is `"license": "ISC",`

**Comment by patricksmms** [comment]
@evilebottnawi, sorry. I just corrected it.

**Comment by patricksmms** [comment]
@geelen, @markdalgleish, @sokra, any chance of getting this published?

**Comment by alexander-akait** [comment]
@patricksmms Don't worry will be fixed in near future

**Pull request merged**
